# Generated by Django 4.1.4 on 2023-01-10 06:02

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "to do": "A place that has not been traveled to yet"
    }
    Status = apps.get_model("wishes","Status")
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishStatus',
            new_name='Status',
        ),
    ]
