# Generated by Django 4.1.4 on 2023-01-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_rename_wishstatus_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='WishStatus',
        ),
    ]
